import { jsPDF } from "jspdf";

// Builds a simple, print-ready prescription/consultation summary PDF and
// triggers a browser download. Kept dependency-light: one page, no images.
export function downloadConsultationPdf(consultation, { patientName, familyMemberName } = {}) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 56;
  let y = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(11, 110, 91);
  doc.text("MediSphere", margin, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90, 90, 90);
  y += 16;
  doc.text("AI-assisted patient case summary", margin, y);

  y += 24;
  doc.setDrawColor(220, 224, 222);
  doc.line(margin, y, 595 - margin, y);

  y += 28;
  doc.setTextColor(20, 32, 27);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Patient", margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(familyMemberName || patientName || "—", margin + 90, y);

  y += 20;
  doc.setFont("helvetica", "bold");
  doc.text("Date", margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(
    consultation.completed_at
      ? new Date(consultation.completed_at).toLocaleString()
      : new Date(consultation.created_at).toLocaleString(),
    margin + 90,
    y
  );

  y += 20;
  doc.setFont("helvetica", "bold");
  doc.text("Status", margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(consultation.status, margin + 90, y);

  if (consultation.severity && consultation.severity !== "routine") {
    y += 20;
    doc.setFont("helvetica", "bold");
    doc.text("Priority", margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(consultation.severity, margin + 90, y);
  }

  y += 32;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Case summary", margin, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  const summaryLines = doc.splitTextToSize(
    consultation.ai_summary || "No summary recorded.",
    595 - margin * 2
  );
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 14 + 20;

  if (consultation.doctor_notes) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Doctor's advice", margin, y);
    y += 16;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    const notesLines = doc.splitTextToSize(consultation.doctor_notes, 595 - margin * 2);
    doc.text(notesLines, margin, y);
    y += notesLines.length * 14 + 20;
  }

  doc.setFontSize(8.5);
  doc.setTextColor(140, 140, 140);
  doc.text(
    "Generated by MediSphere. This is an AI-assisted summary, not a substitute for in-person medical advice.",
    margin,
    780
  );

  doc.save(`medisphere-case-${consultation.id.slice(0, 8)}.pdf`);
}
